Web/RentARoom.Web/Areas/Administration/Controllers/CategoriesController.cs
namespace RentARoom.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using RentARoom.Data;
    using RentARoom.Data.Common.Models;
    using RentARoom.Data.Common.Repositories;
    using RentARoom.Data.Models;

    [Area("Administration")]
    public class CategoriesController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Category> dataRepository;

        public CategoriesController(IDeletableEntityRepository<Category> dataRepository)
        {
            this.dataRepository = dataRepository;
        }

        // GET: Administration/Categories
        public async Task<IActionResult> Index()
        {
            return this.View(await this.dataRepository.AllWithDeleted().ToListAsync());
        }

        // GET: Administration/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.dataRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        // GET: Administration/Categories/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Administration/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Category category)
        {
            if (this.ModelState.IsValid)
            {
                await this.dataRepository.AddAsync(category);
                await this.dataRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(category);
        }

        // GET: Administration/Categories/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = this.dataRepository.All().FirstOrDefault(x => x.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        // POST: Administration/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Category category)
        {
            if (id != category.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.dataRepository.Update(category);
                    await this.dataRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.CategoryExists(category.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(category);
        }

        // GET: Administration/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.dataRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        // POST: Administration/Categories/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = this.dataRepository.All().FirstOrDefault(x => x.Id == id);
            this.dataRepository.Delete(category);
            await this.dataRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool CategoryExists(int id)
        {
            return this.dataRepository.All().Any(e => e.Id == id);
        }
    }
}

Web/RentARoom.Web/Controllers/BookingController.cs
namespace RentARoom.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using RentARoom.Common;
    using RentARoom.Data.Common.Models;
    using RentARoom.Services.Data;
    using RentARoom.Web.ViewModels;
    using RentARoom.Web.ViewModels.Hotels;

    public class BookingController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IHotelsServices hotelsServices;
        private readonly IWebHostEnvironment environment;

        public BookingController(
            ICategoriesService categoriesService,
            IHotelsServices hotelsServices,
            IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.hotelsServices = hotelsServices;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult Add()
        {
            var viewModel = new ViewModels.Hotels.AddHotelsInputViewModel
            {
                CategoriesItems = this.categoriesService.GetAllKeysValuePairs(),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddHotelsInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            try
            {
                await this.hotelsServices.CreateAsync(input, userId, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(input);
            }

            return this.RedirectToAction("ThankYou");
        }

        public IActionResult ThankYou()
        {
            return this.View();
        }

        public IActionResult MostPopular(int id = 1)
        {
            const int itemsPerPage = 12;

            var viewModel = new HotelListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                HotelsCount = this.hotelsServices.GetCount(),
                Hotels = this.hotelsServices.GetMostPopular<HotelInListViewModel>(id, itemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var hotel = this.hotelsServices.GetById<SingleHotelViewModel>(id);
            return this.View(hotel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var inputModel = this.hotelsServices.GetById<EditHotelInputViewModel>(id);
            inputModel.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
            return this.View(inputModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditHotelInputViewModel input)
        {
            var inputModel = this.hotelsServices.GetById<EditHotelInputViewModel>(id);
            if (!this.ModelState.IsValid)
            {
                inputModel.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(inputModel);
            }

            await this.hotelsServices.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.hotelsServices.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.MostPopular));
        }

        public IActionResult Images(int id)
        {
            var inputModel = this.hotelsServices.GetById<ImagesHotelViewModel>(id);

            return this.View(inputModel);
        }
    }
}

Web/RentARoom.Web/Controllers/SearchHotelsController.cs
namespace RentARoom.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using RentARoom.Services.Data;
    using RentARoom.Web.ViewModels.Hotels;
    using RentARoom.Web.ViewModels.SearchHotels;

    public class SearchHotelsController : BaseController
    {
        private readonly IHotelsServices hotelService;
        private readonly IServiceService serviceService;

        public SearchHotelsController(
            IHotelsServices hotelService,
            IServiceService serviceService)
        {
            this.hotelService = hotelService;
            this.serviceService = serviceService;
        }

        public IActionResult Index()
        {
            var viewModel = new SearchIndexViewModel
            {
               Services = this.serviceService.GetAllPopular<ServiceNameViewModel>(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var viewModel = new ListViewModel
            {
                Hotels = this.hotelService
                .GetByServices<HotelInListViewModel>(input.Services),
            };
            return this.View(viewModel);
        }
    }
}

Web/RentARoom.Web/Views/Shared/_CardPartial.cshtml
@model RentARoom.Web.ViewModels.Hotels.HotelListViewModel

<div class="row">
    @foreach (var hotel in this.Model.Hotels)
    {
<div class="col-md-6 col-lg-4 col-xxl-3 p-3">
    <div class="component">
        <div class="card">
            <img src="@hotel.ImageUrl" class="card-img-top" width="100">
            <div class="card-body">
                <h5 class="card-title">@hotel.Name</h5>
                <p class="card-text">@hotel.CategoryName</p>
                <a asp-action="ById" asp-route-id="@hotel.Id" class="btn btn-primary">View Hotel</a>
            </div>
        </div>

    </div>

</div>}
</div>

Web/RentARoom.Web/Views/Shared/_Layout.cshtml
@using RentARoom.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/layout.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/lazy.css" rel="stylesheet" />
    <script src="~/js/maxheight.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/lazy.css" asp-append-version="true">
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid custom-container">
                <a class="custom-title" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchHotels" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="MostPopular">BestRating</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                    <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Add">Create Hotel</a></li>
}
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                    <li class="nav-item"> <a class="nav-link text-dark" asp-area="Administration" asp-controller="Categories" asp-action="Index">CategoriesAdmin</a></li>
}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid custom-container h-100">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="h-100">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/lazy.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/maxheight.js"></script>
    <script src="~/js/jquery.min.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/RentARoom.Web/Views/Shared/_PagingPartial.cshtml
@model RentARoom.Web.ViewModels.Hotels.PagingViewModel
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item @if (!Model.HasPreviousPage) {<text>disabled</text> } ">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item"><a class="page-link">@Model.PageNumber</a></li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {<text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>