Web/RentARoom.Web/Controllers/BookingController.cs
namespace RentARoom.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using RentARoom.Common;
    using RentARoom.Data.Common.Models;
    using RentARoom.Services.Data;
    using RentARoom.Web.ViewModels;
    using RentARoom.Web.ViewModels.Hotels;

    public class BookingController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IHotelsServices hotelsServices;
        private readonly IWebHostEnvironment environment;

        public BookingController(
            ICategoriesService categoriesService,
            IHotelsServices hotelsServices,
            IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.hotelsServices = hotelsServices;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult Add()
        {
            var viewModel = new ViewModels.Hotels.AddHotelsInputViewModel
            {
                CategoriesItems = this.categoriesService.GetAllKeysValuePairs(),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddHotelsInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            try
            {
                await this.hotelsServices.CreateAsync(input, userId, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(input);
            }

            return this.RedirectToAction("ThankYou");
        }

        public IActionResult ThankYou()
        {
            return this.View();
        }

        public IActionResult MostPopular(int id = 1)
        {
            const int itemsPerPage = 12;

            var viewModel = new HotelListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                HotelsCount = this.hotelsServices.GetCount(),
                Hotels = this.hotelsServices.GetMostPopular<HotelInListViewModel>(id, itemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var hotel = this.hotelsServices.GetById<SingleHotelViewModel>(id);
            return this.View(hotel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var inputModel = this.hotelsServices.GetById<EditHotelInputViewModel>(id);
            inputModel.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
            return this.View(inputModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditHotelInputViewModel input)
        {
            var inputModel = this.hotelsServices.GetById<EditHotelInputViewModel>(id);
            if (!this.ModelState.IsValid)
            {
                inputModel.CategoriesItems = this.categoriesService.GetAllKeysValuePairs();
                return this.View(inputModel);
            }

            await this.hotelsServices.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.hotelsServices.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.MostPopular));
        }

        public IActionResult Images(int id)
        {
            var inputModel = this.hotelsServices.GetById<ImagesHotelViewModel>(id);

            return this.View(inputModel);
        }
    }
}

Web/RentARoom.Web/Controllers/ReservationController.cs
namespace RentARoom.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using RentARoom.Data.Common.Repositories;
    using RentARoom.Data.Models;
    using RentARoom.Services.Data;
    using RentARoom.Web.ViewModels.Reservation;
    using RentARoom.Web.Views.Reservation;

    public class ReservationController : Controller
    {
        private readonly IReservationService reservationService;
        private readonly IDeletableEntityRepository<Hotel> hotelRepository;

        public ReservationController(
            IReservationService reservationService,
            IDeletableEntityRepository<Hotel> hotelRepository)
        {
            this.reservationService = reservationService;
            this.hotelRepository = hotelRepository;
        }

        public IActionResult New(int id)
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> New(ReservationInputModel input, int id)
        {
            var hotelName = this.hotelRepository.All().FirstOrDefault(x => x.Id == id).Name;
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var result = await this.reservationService.AddReservation(input.ChechIn, input.CheckOut, hotelName, input.NumberOfPeople, userId);
            if (result >= 0)
            {
                return this.RedirectToAction("ThankYou");
            }

            return this.NotFound();
        }

        public IActionResult ThankYou()
        {
            return this.View();
        }
    }
}

Web/RentARoom.Web/Views/Booking/Add.cshtml
@model RentARoom.Web.ViewModels.Hotels.AddHotelsInputViewModel
@{ this.ViewData["Title"] = "Add new hotel";
                var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key)); }

<h1 class="mb-4 text-center">@this.ViewData["Title"]</h1>

<form method="post" class="col-md-6 offset-md-3"
      enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group mb-2">
        <label asp-for="Image" class="pb-1"></label>
        <input asp-for="Image" class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Name" class="pb-1"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Town" class="pb-1"></label>
        <input asp-for="Town" class="form-control" />
        <span asp-validation-for="Town" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Address" class="pb-1"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Stars" class="pb-1"></label>
        <input asp-for="Stars" class="form-control" />
        <span asp-validation-for="Stars" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="CountRooms" class="pb-1"></label>
        <input asp-for="CountRooms" class="form-control" />
        <span asp-validation-for="CountRooms" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="CategoryId" class="pb-1"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Bed" class="pb-1"></label>
        <input asp-for="Bed" class="form-control" />
        <span asp-validation-for="Bed" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Capacity" class="pb-1"></label>
        <input asp-for="Capacity" class="form-control" />
        <span asp-validation-for="Capacity" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Price" class="pb-1"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Description" class="pb-1"></label>
        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div id="ServicesContainer" class="mb-4">
        <div class="mb-2">
            <label asp-for="Services" class="pb-1"></label>
            <a class="btn btn-success" onclick="AddMoreServices()">+</a>
        </div>

        </div>
        <input type="submit" class="btn btn-primary" />
</form>
@*'Services[" + serviceIndex + "].Name'*@
@section Scripts{
    <script>
        var serviceIndex = 0;
        function AddMoreServices() {
            console.log("AddMoreServices")
            $("#ServicesContainer").append("<div class='mb-2'><label class='pb-1'>Service:</label> <input class='form-control' type='text' name='Services[" + serviceIndex + "].ServiceName'/></div>");
            serviceIndex++;
        }
    </script>
}

Web/RentARoom.Web/Views/Booking/ById.cshtml
@using RentARoom.Common
@model RentARoom.Web.ViewModels.Hotels.SingleHotelViewModel;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="~/js/maxheight.js"></script>
    <link href="~/css/layout.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body class="brown-background" id="page1" onload="new ElementMaxHeight();">
    <div id="main">
        <div id="header">
            <div class="row-2">
                <div class="indent">
                    <!-- header-box begin -->
                    <div class="header-box">
                        <img class="custom-image" src="@Model.ImageUrl" alt="@Model.Name" />
                        <div class="inner">
                            <ul class="nav">
                                <li><a href="index.html" class="current">Home page</a></li>
                                <li><a asp-action="Images" asp-route-id="@Model.Id">Gallery</a></li>
                                <li><a asp-controller="Reservation" asp-action="New" asp-route-id="@Model.Id">Booking</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- header-box end -->
                </div>
            </div>

        </div>
        <div id="content">
            <div class="wrapper">
                <div class="aside maxheight">
                    <!-- box begin -->
                    <div class="box maxheight">
                        <div class="inner">
                          
                        </div>
                    </div>
                    <!-- box end -->
                </div>
                <div class="content">
                    <div class="indent">
                        <h2>@Model.Name is happy to welcome you!</h2>
                        <img class="img-indent png" alt="" src="images/1page-img1.png" />
                        <p class="alt-top">@Model.Description</p>
                        Feel free to contact us anytime in case you have any questions or concerns.
                        <div class="clear"></div>
                        <div class="line-hor"></div>
                        <div class="wrapper line-ver">
                            <div class="col-1">
                                <h3>Special Offers</h3>
                                <ul >
                                    @foreach (var service in Model.Services)
                                    {
                                        <li class="custom-service-item">
                                            @service.ServiceName
                                        </li>
                                    }

                                </ul>
                            </div>
                            <div class="col-2">
                                <h3>Location</h3>
                                <p>We are located in the @Model.Town</p>
                                <dl class="contacts-list">
                                    <dt>@Model.Address</dt>
                                </dl>
                            </div>
                            <div class="rating">
                                <ul class="item-rating d-flex flex-row">
                                    <li class="star-fill mx-1 list-unstyled" data-vote="1">
                                        @if (Model.AverageVote >= 1.0 && Model.AverageVote < 2.0)
                                        {
                                            <i class="fas fa-star color-yellow"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-star"></i>
                                        }
                                    </li>
                                    <li class="star-fill mx-1 list-unstyled" data-vote="2">
                                        @if (Model.AverageVote >= 2.0 && Model.AverageVote < 3.0)
                                        {
                                            <i class="fas fa-star color-yellow"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-star"></i>
                                        }
                                    </li>
                                    <li class="star-fill mx-1 list-unstyled" data-vote="3">
                                        @if (Model.AverageVote >= 3.0 && Model.AverageVote < 4.0)
                                        {
                                            <i class="fas fa-star color-yellow"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-star"></i>
                                        }
                                    </li>
                                    <li class="star-fill mx-1 list-unstyled" data-vote="4">
                                        @if (Model.AverageVote >= 4.0 && Model.AverageVote < 5.0)
                                        {
                                            <i class="fas fa-star color-yellow"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-star"></i>
                                        }
                                    </li>
                                    <li class="star-fill mx-1 list-unstyled" data-vote="5">
                                        @if (Model.AverageVote == 5.0)
                                        {
                                            <i class="fas fa-star color-yellow"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-star"></i>
                                        }
                                    </li>
                                    <li><span id="averageVoteValue">@Model.AverageVote.ToString("0.0")</span><span> / 5</span> </li>
                                </ul>
                            </div>
                            <div class="d-flex flex-row">
                                @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                                {
                                    <a asp-controller="Booking" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary ">Edit</a>
                                    <form method="post" asp-action="Delete" id="deleteForm" asp-route-id="@Model.Id">
                                    </form>
                                    <button  type="submit" class="btn btn-danger mx-4" value="Delete" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    @*footer*@
    <script src="~/js/maxheight.js"></script>
    <form method="post" id="antiForgeryForm"></form>
    @section Scripts {
        <script>
        $("li[data-vote]").each(function (el) {
            $(this).click(function () {
                var value = +$(this).attr("data-vote");
                var hotelId = @Model.Id;
                var antiForgeryToken = $('#antiForgeryForm input[name=__RequestVerificationToken]').val();
                var data = { hotelId: hotelId, value: value };
                $.ajax({
                    type: "POST",
                    url: "/api/Votes",
                    data: JSON.stringify(data),
                    headers: {
                        'X-CSRF-TOKEN': antiForgeryToken
                    },
                    success: function (data) {
                        const activeStar = $(`i.color-yellow`);
                        $(activeStar).removeClass('color-yellow');

                        const newActiveListItem = $(`li[data-vote=${Math.floor(data.averageVote)}]`)

                        $(newActiveListItem).html("<i class='fas fa-star color-yellow'></i>")
                        $('#averageVoteValue').html(data.averageVote.toFixed(1));
                    },
                    contentType: 'application/json',
                });
            })
        });
        </script>
    }
</body>

</html>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete @Model.Name?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" onclick="deleteForm.submit()">Yes</button>
            </div>
        </div>
    </div>
</div>

Web/RentARoom.Web/Views/Booking/Edit.cshtml
@model RentARoom.Web.ViewModels.Hotels.EditHotelInputViewModel
@{
    ViewData["Title"] = "Edit Hotel";
    var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}
<h1>@ViewData["Title"]</h1>

<form method="post" id="editForm">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Town"></label>
        <input asp-for="Town" class="form-control" />
        <span asp-validation-for="Town" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" asp-items="categoryItems" class="form-control"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea> 
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <hr />
    <input type="hidden" asp-for="Id" />
</form>
   <button type="submit" class="btn btn-success" value="Save Changes" data-bs-toggle="modal" data-bs-target="#modalEdit">Save changes</button>

<div class="modal fade" id="modalEdit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Edit</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you confirm this changes?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="editForm.submit()">Save changes</button>
            </div>
        </div>
    </div>
</div>

Web/RentARoom.Web/Views/Booking/Images.cshtml
@model RentARoom.Web.ViewModels.ImagesHotelViewModel
@{ this.ViewData["Title"] = $"All images on  hotel {Model.Name}!"; }

<h1 class="mb-4 text-center">@this.ViewData["Title"]</h1>

<div class="row">

    @foreach (var image in Model.Images)
    {

<div class="col-md-6 col-lg-4 p-3">
    <div class="component">
        <div class="card">

            <img class="custom-image rounded" src="~/images/hotels/@image.Id.@image.Extension" alt="@Model.Name" />
        </div>
    </div>
</div>}
</div>

Web/RentARoom.Web/Views/Booking/MostPopular.cshtml
@model RentARoom.Web.ViewModels.Hotels.HotelListViewModel
@{ this.ViewData["Title"] = "Best rating hotel"; }

<h1 class="mb-4 text-center">@this.ViewData["Title"]</h1>

<partial name="_CardPartial" model="@Model" />
<hr />
<partial name="_PagingPartial" model="@Model" />

Web/RentARoom.Web/Views/Booking/ThankYou.cshtml
@{
    this.ViewData["Title"] = "Thank You";
}

<h1 class="text-center">@this.ViewData["Title"]</h1>